<div style="padding: 10px; background-color: rgb(40, 43, 51); color: rgb(255, 255, 255);" id="item_0"><h1 style="padding-left: 10px; padding-right: 10px; text-align: center; font-size: 40px;" id="item_9" editable="true">Testimonials</h1><div style="display: flex; flex-wrap: wrap; max-width: 1200px; margin: auto;" id="item_1">
	<div style="flex: 1 1 0%; min-width: 400px; min-height: 200px; vertical-align: top; display: flex; justify-content: center; align-items: center; color: rgb(255, 255, 255);" id="item_2"><img ondragstart="return false" src="images/segment_images/people/beautiful-sincere-happy-girl-smiling-laughing_176420-9693.jpg" style="border-radius: 50%; width: 100px; height: 100px; object-fit: cover; border: 10px solid rgb(231, 91, 43);" id="item_4"><div style="padding: 10px; color: rgb(0, 0, 0); flex: 1 1 1%;" id="item_6"><div style="padding: 5px; color: rgb(239, 239, 239);" id="item_5" editable="true">There are many variations of passages of Lorem Ipsum available, but the 
majority have suffered alteration in some form, by injected humour, or 
randomised words which don't look even slightly believable</div><h4 style="padding-left: 10px; padding-right: 10px; margin: 10px 0px 0px; text-transform: uppercase; color: rgb(231, 91, 43);" id="item_7" editable="true">Jane Doe<br></h4></div></div>
	
<div style="flex: 1 1 0%; min-width: 400px; min-height: 200px; vertical-align: top; display: flex; justify-content: center; align-items: center; color: rgb(255, 255, 255);" id="item_8"><img ondragstart="return false" src="images/segment_images/people/candid-shot-serious-european-lady-makes-shush-gesture-keesp-index-finger-lips_273609-44692.jpg" style="border-radius: 50%; width: 100px; height: 100px; object-fit: cover; border: 10px solid rgb(231, 91, 43);" id="item_4"><div style="padding: 10px; color: rgb(0, 0, 0); flex: 1 1 1%;" id="item_6"><div style="padding: 5px; color: rgb(239, 239, 239);" id="item_5" editable="true">Contrary to popular belief, Lorem Ipsum is not simply random text. It 
has roots in a piece of classical Latin literature from 45 BC, making it
 over 2000 years old</div><h4 style="padding-left: 10px; padding-right: 10px; margin: 10px 0px 0px; text-transform: uppercase; color: rgb(231, 91, 43);" id="item_7" editable="true">MIRIAM PHIRI <br></h4></div></div></div><div style="display: flex; flex-wrap: wrap; max-width: 1200px; margin: auto;" id="item_10">
	<div style="flex: 1 1 0%; min-width: 400px; min-height: 200px; vertical-align: top; display: flex; justify-content: center; align-items: center; color: rgb(255, 255, 255);" id="item_2"><img ondragstart="return false" src="images/segment_images/people/excited-smiling-curly-haired-girl-showing-credit-card-paying-online-order-using-smartphone_176420-20206.jpg" style="border-radius: 50%; width: 100px; height: 100px; object-fit: cover; border: 10px solid rgb(231, 91, 43);" id="item_4"><div style="padding: 10px; color: rgb(0, 0, 0); flex: 1 1 1%;" id="item_6"><div style="padding: 5px; color: rgb(239, 239, 239);" id="item_5" editable="true">Contrary to popular belief, Lorem Ipsum is not simply random text. It 
has roots in a piece of classical Latin literature from 45 BC, making it
 over 2000 years old</div><h4 style="padding-left: 10px; padding-right: 10px; margin: 10px 0px 0px; text-transform: uppercase; color: rgb(231, 91, 43);" id="item_7" editable="true">CRISTY MAN<br></h4></div></div>
	
<div style="flex: 1 1 0%; min-width: 400px; min-height: 200px; vertical-align: top; display: flex; justify-content: center; align-items: center; color: rgb(255, 255, 255);" id="item_8"><img ondragstart="return false" src="images/segment_images/people/close-up-portrait-attractive-man-with-afro-hairstyle-stubble-wears-orange-anorak_273609-8595.jpg" style="border-radius: 50%; width: 100px; height: 100px; object-fit: cover; border: 10px solid rgb(231, 91, 43);" id="item_4"><div style="padding: 10px; color: rgb(0, 0, 0); flex: 1 1 1%;" id="item_6"><div style="padding: 5px; color: rgb(239, 239, 239);" id="item_5" editable="true">There are many variations of passages of Lorem Ipsum available, but the 
majority have suffered alteration in some form, by injected humour, or 
randomised words which don't look even slightly believable</div><h4 style="padding-left: 10px; padding-right: 10px; margin: 10px 0px 0px; text-transform: uppercase; color: rgb(231, 91, 43);" id="item_7" editable="true">TOM Njovu<br></h4></div></div></div><div style="display: flex; flex-wrap: wrap; max-width: 1200px; margin: auto;" id="item_11">
	<div style="flex: 1 1 0%; min-width: 400px; min-height: 200px; vertical-align: top; display: flex; justify-content: center; align-items: center; color: rgb(255, 255, 255);" id="item_2"><img ondragstart="return false" src="images/segment_images/people/close-up-shot-ordinary-fair-haired-caucasian-male-with-bristle-earrings-staring-carefree-being-indifferent-calm_176420-25002.jpg" style="border-radius: 50%; width: 100px; height: 100px; object-fit: cover; border: 10px solid rgb(231, 91, 43);" id="item_4"><div style="padding: 10px; color: rgb(0, 0, 0); flex: 1 1 1%;" id="item_6"><div style="padding: 5px; color: rgb(239, 239, 239);" id="item_5" editable="true">There are many variations of passages of Lorem Ipsum available, but the 
majority have suffered alteration in some form, by injected humour, or 
randomised words which don't look even slightly believable</div><h4 style="padding-left: 10px; padding-right: 10px; margin: 10px 0px 0px; text-transform: uppercase; color: rgb(231, 91, 43);" id="item_7" editable="true">PETER STEEL<br></h4></div></div>
	
<div style="flex: 1 1 0%; min-width: 400px; min-height: 200px; vertical-align: top; display: flex; justify-content: center; align-items: center; color: rgb(255, 255, 255);" id="item_8"><img ondragstart="return false" src="images/segment_images/people/close-up-shot-pretty-woman-with-perfect-teeth-dark-clean-skin-having-rest-indoors-smiling-happily-after-received-good-positive-news_273609-1248.jpg" style="border-radius: 50%; width: 100px; height: 100px; object-fit: cover; border: 10px solid rgb(231, 91, 43);" id="item_4"><div style="padding: 10px; color: rgb(0, 0, 0); flex: 1 1 1%;" id="item_6"><div style="padding: 5px; color: rgb(239, 239, 239);" id="item_5" editable="true">Contrary to popular belief, Lorem Ipsum is not simply random text. It 
has roots in a piece of classical Latin literature from 45 BC, making it
 over 2000 years old</div><h4 style="padding-left: 10px; padding-right: 10px; margin: 10px 0px 0px; text-transform: uppercase; color: rgb(231, 91, 43);" id="item_7" editable="true">JaneT DAKa<br></h4></div></div></div></div>