<section style="width: 100%; background-color: rgb(255, 255, 255);" id="item_0" vw=""><div style="color: rgb(255, 255, 255); max-width: 850px; margin: auto;" id="item_1"><div style="display: flex;flex-wrap:wrap;" id="item_2">
	<div style="flex: 1;min-width:300px;min-height: 200px;background-color: #f2f2f2;vertical-align: top;" id="item_3"><img ondragstart="return false" src="images/segment_images/people/candid-shot-serious-european-lady-makes-shush-gesture-keesp-index-finger-lips_273609-44692.jpg" style="width: 100%; height: 100%; object-fit: cover;" id="item_8"></div>
	<div style="flex: 1 1 0%; min-width: 300px; min-height: 200px; background-color: rgb(255, 78, 90); vertical-align: top; color: rgb(255, 255, 255); text-align: center;" id="item_4"><h1 style="padding-left: 10px; padding-right: 10px; font-size: 30px;" id="item_9" editable="true">Hello!<br></h1><h4 style="padding-left: 10px; padding-right: 10px; font-size: 20px;" id="item_10" editable="true">i'm a multitalented creative web designer<br></h4><div style="padding: 15px;" id="item_11" editable="true">It is a long established fact that a reader will be distracted by the 
readable content of a page when looking at its layout. The point of 
using Lorem Ipsum is that it has a more-or-less normal distribution of 
letters, as opposed to using 'Content here, content here', making it 
look like readable English. Many desktop publishing packages and web 
page editors now use Lorem Ipsum as their default model text, and a 
search for 'lorem ipsum' will uncover many web sites still in their 
infancy</div><div style="padding:10px;color: #FFFFFFFF;" id="item_12"><i class="bi bi-facebook" style="font-size: 30px; margin-left: 10px; margin-right: 10px;"></i><i class="bi bi-twitter" style="font-size: 30px; margin-left: 10px; margin-right: 10px;" id="item_13"></i><i class="bi bi-instagram" style="font-size: 30px; margin-left: 10px; margin-right: 10px;" id="item_14"></i></div></div>
</div><div style="display: flex;flex-wrap:wrap;" id="item_5">
	<div style="flex: 1 1 0%; min-width: 300px; min-height: 200px; background-color: rgb(255, 78, 90); vertical-align: top; color: rgb(255, 255, 255); text-align: center; padding-top: 10px; padding-bottom: 10px;" id="item_6"><h1 style="padding-left: 10px; padding-right: 10px; font-size: 30px; margin: 0px;" id="item_15" editable="true">Details<br></h1><h3 style="padding-left: 10px; padding-right: 10px; margin: 10px 0px 0px; text-transform: uppercase;" id="item_16" editable="true">Name</h3><div style="padding: 5px; font-size: 18px;" id="item_17" editable="true">Peter Ransom<br></div><h3 style="padding-left: 10px; padding-right: 10px; margin: 10px 0px 0px; text-transform: uppercase;" id="item_18" editable="true">Role</h3><div style="padding: 5px; font-size: 18px;" id="item_19" editable="true">Lead Web Designer<br></div><h3 style="padding-left: 10px; padding-right: 10px; margin: 10px 0px 0px; text-transform: uppercase;" id="item_20" editable="true">Email</h3><div style="padding: 5px; font-size: 18px;" id="item_22" editable="true">peter@designer.com<br></div><h3 style="padding-left: 10px; padding-right: 10px; margin: 10px 0px 0px; text-transform: uppercase;" id="item_23" editable="true">Phone</h3><div style="padding: 5px; font-size: 18px;" id="item_25" editable="true">1 (987) 567-224<br></div><h3 style="padding-left: 10px; padding-right: 10px; margin: 10px 0px 0px; text-transform: uppercase;" id="item_27" editable="true">Website</h3><div style="padding: 5px; font-size: 18px;" id="item_28" editable="true">www.samplewebsite.com<br></div></div>
	<div style="flex: 1 1 0%; min-width: 300px; min-height: 200px; background-color: rgb(241, 241, 241); vertical-align: top;" id="item_7"><div style="display: flex;flex-wrap:wrap;" id="item_29">
	<div style="flex: 1 1 0%; min-width: 150px; min-height: 200px; vertical-align: top; color: rgb(101, 101, 101); text-align: center; display: flex; flex-direction: column; place-content: center; align-items: center;" id="item_30"><h3 style="padding-left: 10px; padding-right: 10px; margin: 10px 0px 0px; text-transform: uppercase; left: -5px;" id="item_32" editable="true">Years experience<br></h3><h1 style="padding-left: 10px; padding-right: 10px; font-size: 3.5em; color: rgb(255, 78, 90); margin: 0px; font-family: tahoma;" id="item_33" editable="true">15+</h1></div>
	
<div style="flex: 1 1 0%; min-width: 150px; min-height: 200px; vertical-align: top; color: rgb(101, 101, 101); text-align: center; display: flex; flex-direction: column; place-content: center; align-items: center;" id="item_34"><h3 style="padding-left: 10px; padding-right: 10px; margin: 10px 0px 0px; text-transform: uppercase; left: -5px;" id="item_32" editable="true">Awards<br></h3><h1 style="padding-left: 10px; padding-right: 10px; font-size: 3.5em; color: rgb(255, 78, 90); margin: 0px; font-family: tahoma;" id="item_33" editable="true">13</h1></div><div style="flex: 1 1 0%; min-width: 150px; min-height: 200px; vertical-align: top; color: rgb(101, 101, 101); text-align: center; display: flex; flex-direction: column; place-content: center; align-items: center;" id="item_35"><h3 style="padding-left: 10px; padding-right: 10px; margin: 10px 0px 0px; text-transform: uppercase; left: -5px;" id="item_32" editable="true">Projects</h3><h1 style="padding-left: 10px; padding-right: 10px; font-size: 3.5em; color: rgb(255, 78, 90); margin: 0px; font-family: tahoma;" id="item_33" editable="true">178</h1></div><div style="flex: 1 1 0%; min-width: 150px; min-height: 200px; vertical-align: top; color: rgb(101, 101, 101); text-align: center; display: flex; flex-direction: column; place-content: center; align-items: center;" id="item_36"><h3 style="padding-left: 10px; padding-right: 10px; margin: 10px 0px 0px; text-transform: uppercase; left: -5px;" id="item_32" editable="true">Clients</h3><h1 style="padding-left: 10px; padding-right: 10px; font-size: 3.5em; color: rgb(255, 78, 90); margin: 0px; font-family: tahoma;" id="item_33" editable="true">345</h1></div></div></div>
</div></div></section>